name: complex-constrained-decoding-eval
channels:
  - conda-forge
  - nvidia # nvidia channel for cuda packages
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.11 # or don't specify the version and use latest stable

  # ML libraries
  - pytorch::pytorch>=2.0 # or don't specify the version and use latest stable
  # CUDA only on linux and windows
  - pytorch::pytorch-cuda=11.8 # [linux]
  - pytorch::pytorch-cuda=11.8 # [win]
  
  - wandb
  - lightning
  - transformers
  # - tokenizers
  #- datasets 3.6 is broken and earlier as well, so we use git version
  - evaluate
  - accelerate
  - sentencepiece


  - langdetect
  - nltk

  # Good to have
  - numpy
  - scipy
  - pandas
  - seqeval
  - scikit-learn 

  # Misc
  - jsonlines
  - zstandard
  - debugpy
  - tqdm
  - libsqlite


  # Dev dependencies
  - black
  - ruff
  - ipykernel

  # pip dependencies
  - pip
  - pip:
      - pipx
      - simple_parsing
      - print-on-steroids[exceptions]
      - ollama
      - absl-py
      - immutabledict
      - vllm>0.8
      - bert_score
      - huggingface_hub[hf_xet]
      - datasets>=4
      - tokenizers<0.21.3

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
  # - osx-arm64 # This is for M1/M2 MacBooks # Note: needs mamba 1.5.3 to work properly
  # - linux-aarch64 # This is linux-arm64. We can build Docker images for M1/M2 Macs on top of this - won't support MPS though
  # - win-64
